account/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = "account"
urlpatterns = [

    url(r'^login/', views.login_user, name='login'),
    url(r'^register/', views.register_user, name='register'),
    url(r'^logout/', views.logout_user, name='logout'),
    url(r'^forget', views.forget_password, name='forget-password'),
    url(r'^view', views.account_profile, name='profile'),
    path('reset/', views.reset_password, name='reset-password'),
    path('reset/<uuid:token>/', views.reset_password, name='reset-password'),
]

home/urls.py
from django.conf.urls import url

from . import views

app_name = "home"
urlpatterns = [
    url(r'^$', views.index, name='index')
]

tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include("account.urls")),
    path('uploader/', include("uploader.urls"))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

uploader/urls.py
from django.conf.urls import url

from . import views
from . import consumers

app_name = "uploader"
urlpatterns = [

    url(r'^$', views.uploader, name='uploader'),
    url(r'^disabled/$', views.disabled, name='disabled')
]

websocket_urlpatterns = [
    url(r'^ws/uploader$', consumers.UploadConsumer)
]

templates/base/base.html
{% load static %}
<html>

<head>
    {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/jquery.serialize-object.min.js' %}"></script>

        <script src="{% static 'js/api.js' %}"></script>
        <script src="{% static 'js/global.js' %}"></script>

        <link rel="stylesheet" href="{% static 'semantic/semantic.min.css' %}"/>
        <script src="{% static 'semantic/semantic.min.js' %}"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'navbar/css/navbar.css' %}"/>
        <script src="{% static 'navbar/js/navbar.js' %}"></script>

        {# Can maybe check for authentication to not load it #}

        <link href="{% static 'css/pretty-checkbox.min.css' %}" media="all"
              rel="stylesheet" type="text/css"/>
        <link rel="stylesheet" href="{% static 'css/main.css' %}" />

    {% endblock %}
</head>

<body>
{% include 'base/navbar.html' %}
{% block content %}
{% endblock %}
</body>
<footer>
    {% block footer %}
    {% endblock %}
</footer>
</html>

templates/base/navbar.html
{% load is_active %}
<div class="ui grid">
    <div class="computer tablet only row">
        <div class="ui fixed menu navbar grid">
            <a href="{% url 'home:index' %}" class="brand item">ReSurfed</a>
            <a href="{% url 'home:index' %}" class="{% is_active request 'home:index' %} item">Home</a>
            {% if user.is_authenticated %}
            <a href="{% url 'uploader:uploader' %}" class="{% is_active request 'uploader:uploader' %} item">Map Management</a>
            {% endif %}

            <div class="right menu">
                {% if not user.is_authenticated %}
                    <a href="{% url 'account:login' %}" class="item">Log In</a>
                    <a href="{% url 'account:register' %}" class="item">Register</a>
                {% else %}

                    <div class="ui dropdown item">Hello {{ user.username }}
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            <a class="item" href="{% url 'account:logout' %}">Sign out</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>